-- constants
GRAVITY = 0.05
TERMINAL_VELOCITY = 3
FLAP_POWER = 1
BIRD_X_MODIFIER = 0.1
BIRD_MAX_X_VELOCITY = 2.5 --1.5
GATOR_CHOMP_SPEED = 0.125
GATOR_HOP_SPEED = 0.1
SPLASH_THROB_SPEED = 0.125
DRONE_BLINK_SPEED = 0.075
FLAG_RAISE_MAX = 9
FLAG_RAISE_SPEED = 0.5
BIRD_MAX_ALTITUDE = -6
SCENE_ADVANCE_COOLDOWN_DURATION = 0.5
BABY_TOSS_VELOCITY_MODIFIER = 0.33
DEBUG = false

function do_nothing() 
    printh()
end

EMPTY_FUNCTION = do_nothing